### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by togo59** [barche/jlqml#1]
Julia-1.1.0 on Kubuntu 16.04

Build went OK but make gave:
`rpowell@rp1:~/jlqml-build$ make
Scanning dependencies of target jlqml_automoc
[  7%] Automatic moc for target jlqml
Generating moc_julia_api.cpp
Generating moc_julia_display.cpp
Generating moc_julia_function.cpp
Generating moc_julia_painteditem.cpp
Generating moc_julia_signals.cpp
Generating moc_listmodel.cpp
Generating moc_makie_viewport.cpp
Generating moc_opengl_viewport.cpp
[  7%] Built target jlqml_automoc
Scanning dependencies of target jlqml
[ 14%] Building CXX object CMakeFiles/jlqml.dir/application_manager.cpp.o
[ 21%] Building CXX object CMakeFiles/jlqml.dir/julia_api.cpp.o
[ 28%] Building CXX object CMakeFiles/jlqml.dir/julia_display.cpp.o
[ 35%] Building CXX object CMakeFiles/jlqml.dir/julia_function.cpp.o
[ 42%] Building CXX object CMakeFiles/jlqml.dir/julia_painteditem.cpp.o
[ 50%] Building CXX object CMakeFiles/jlqml.dir/julia_signals.cpp.o
[ 57%] Building CXX object CMakeFiles/jlqml.dir/listmodel.cpp.o
[ 64%] Building CXX object CMakeFiles/jlqml.dir/makie_viewport.cpp.o
[ 71%] Building CXX object CMakeFiles/jlqml.dir/opengl_viewport.cpp.o
[ 78%] Building CXX object CMakeFiles/jlqml.dir/type_conversion.cpp.o
[ 85%] Building CXX object CMakeFiles/jlqml.dir/wrap_qml.cpp.o
/home/rpowell/jlqml/wrap_qml.cpp: In lambda function:
/home/rpowell/jlqml/wrap_qml.cpp:219:41: error: ‘class QOpenGLFramebufferObject’ has no member named ‘textures’
       qWarning() << "textures: " << fbo.textures();
                                         ^
CMakeFiles/jlqml.dir/build.make:302: recipe for target 'CMakeFiles/jlqml.dir/wrap_qml.cpp.o' failed
make[2]: *** [CMakeFiles/jlqml.dir/wrap_qml.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/jlqml.dir/all' failed
make[1]: *** [CMakeFiles/jlqml.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`
What am I missing?

**Comment by barche** [comment]
Ah, probably your Qt is too old to have that function. This is just a debugging function, so you can safely comment or remove line 219 from `wrap_qml.cpp`.

**Comment by togo59** [comment]
Brilliant! Many thanks.
