### ISSUE TITLE
Will this project work with QT 6.5?

### ISSUE THREAD

**Issue by ufechner7** [barche/jlqml#15]
In the file build_tarballs.jl the following dependencies are defined:
    Dependency("Qt6Base_jll"; compat="6.4.2"),
    Dependency("Qt6ShaderTools_jll", compat="6.4.2"),
    Dependency("Qt6Declarative_jll", compat="6.4.2"),
    HostBuildDependency("Qt6Declarative_jll"),
    Dependency("Qt6Svg_jll", compat="6.4.2"),
    
But in the Project.toml file of QML.jl a dependency on QT 6.5 is defined:
Qt65Compat_jll = "f5784262-74e5-52be-b835-f3e8a3cf8710"

This looks like a contradiction to me, but perhaps I miss something?

**Comment by barche** [comment]
Yes, it already uses Qt6.5, since the `build_tarballs.jl` that is used on release is in Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/blob/b95d2aeed3674f1790cbbb0c301406e4aa925e98/J/jlqml/build_tarballs.jl

**Comment by ufechner7** [comment]
So should build_tarballs.jl be removed here?

**Comment by barche** [comment]
No, it should be updated at some point, but the way JLLs are built in CI now is not ideal anyway, so it's not urgent.

**Comment by barche** [comment]
The JLL build script will move to QML.jl, so this issue is no longer relevant.
