### ISSUE TITLE
Running jlqml with QML.jl does not recognize Math. or Qt. in the qml files

### ISSUE THREAD

**Issue by FrankUrbach** [barche/jlqml#6]
Dear Bart
I've tried many days figuring out how the jlqml-library works. So far so good. If I use a regular Qt-project and compile it. It works like a charme. But if I use the same qml with QML.jl the Types from Qt (Math, Qt, Number etc) will not be recognized. I use Version 1.4.1 on a Mac and compiled the jlqml.dylib successfully on my Mac. I have no clue how to expose these types to the Application. The application starts but when it comes to calculations in the deeper layers of qml errors are thrown all the times. All attempts to correct the error have failed so far. Unfortunately, I have no further idea what the cause might be. Hope you have eventually an idea. 
I have an application in mind where developing the whole stack in Julia would be such a nice experience. 

 Best 
Frank

**Comment by barche** [comment]
This is fixed in the current release.
