### ISSUE TITLE
Julia 1.6.0 build on macOS fails

### ISSUE THREAD

**Issue by jheinen** [barche/jlqml#8]
The binaries provided by BinaryBuilder could not be built on macOS with Julia 1.6.0.

Therefore, I tried to build them myself. Unfortunately, this only works with the following patch:

```
--- jlqml/CMakeLists.txt        2021-04-08 10:32:57.000000000 +0200
+++ jlqml.new/CMakeLists.txt    2021-04-08 10:30:44.000000000 +0200
@@ -57,6 +57,8 @@
 
 target_link_libraries(jlqml Qt5::Core Qt5::Quick Qt5::Svg Qt5::Widgets JlCxx::cxxwrap_julia JlCxx::cxxwrap_julia_stl)
 
+target_link_libraries(jlqml /usr/local/julia/lib/julia/libuv.dylib)
+
 install(TARGETS
   jlqml
 LIBRARY DESTINATION lib
```

**Comment by barche** [comment]
Yes, I have a patch in the works to no longer rely on libuv. It is used by the async event loop (to allow having an active REPL and QML window), but in the mean time I figured out that this use case can be handled much more elegantly by using a `Timer` on the Julia side.
